version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-backend
    command: daphne -b 0.0.0.0 -p 8000 back.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  celery:
    build:
      context: .
      dockerfile: Dockerfile-backend
    command: celery -A back worker --loglevel=info -P solo
    volumes:
      - .:/app

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile-backend
    command: celery -A back beat --loglevel=info
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    volumes:
      - ./front:/app
      - /app/node_modules
