# Dockerfile-frontend
FROM node:18

WORKDIR /app
COPY front/package*.json ./
RUN npm install

COPY front /app

RUN npm run build

# Используем nginx для продакшн-сборки
FROM nginx:stable-alpine
COPY --from=0 /app/build /usr/share/nginx/html
COPY front/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
