services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rEset237?
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build:
      context: .
    command: celery -A back worker --loglevel=info -P solo
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: .
    command: celery -A back beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 back.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis


volumes:
  postgres_data: {}
  redis_data: {}

