# Dockerfile-backend
FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    libpq-dev gcc python3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY back /app/back

WORKDIR /app/back
RUN chmod +x manage.py

EXPOSE 8000

ENV DJANGO_SETTINGS_MODULE=back.settings

CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "back.asgi:application"]
